(()=>{
if(window.__A7_FOOD_V1__)return;window.__A7_FOOD_V1__=1;
const K='isimi_food_cart_v1';
const E=v=>typeof escapeHTML==='function'?escapeHTML(v):String(v??'');
const M=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format((+n||0)/100);
const S=()=>typeof getAuthSession==='function'?getAuthSession():null;
const A=()=>{const s=S();if(!s?.access_token){openAuthModal?.('login');return null}return s};
const Q=(m,p,b=null)=>window.supabaseAuthRequest(m,p,b);
const C=()=>{try{return JSON.parse(localStorage.getItem(K)||'null')||{venue:null,items:[]}}catch(e){return{venue:null,items:[]}}};
const SAVE=c=>localStorage.setItem(K,JSON.stringify(c));const CLEAR=()=>localStorage.removeItem(K);
const CNT=()=>C().items.reduce((n,x)=>n+x.quantity,0);const SUM=()=>C().items.reduce((n,x)=>n+x.line_total_kurus,0);
function css(){if(document.getElementById('a7FoodCss'))return;const s=document.createElement('style');s.id='a7FoodCss';s.textContent='.foodGrid{display:grid;grid-template-columns:1fr;gap:10px}.foodVenue,.foodOrder{padding:14px;border:1px solid var(--line);border-radius:17px;background:var(--card);color:var(--text);text-align:left}.foodItem{display:flex;justify-content:space-between;gap:10px;padding:13px 0;border-bottom:1px solid var(--line)}.foodAdd{width:40px;height:40px;border-radius:11px;border:1px solid var(--line);background:var(--card2);color:var(--text);font-size:20px}.foodCartBar{position:sticky;bottom:64px;z-index:10;margin-top:12px;padding:10px;border:1px solid var(--line);border-radius:15px;background:var(--card);display:flex;gap:8px;align-items:center}.foodCartBar button{flex:1}@media(min-width:720px){.foodGrid{grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
async function showFoodHome(){css();if(!A())return;setNav?.('navFood');app('<div class="foodShell"><div class="foodHero"><div class="small muted">🍽️ İŞİMİ ÇÖZ YEMEK</div><h1>Yakınındaki yemekleri bul.</h1><p class="muted">Yerel işletmelerden keşfet, sipariş ver ve takip et.</p></div><div class="splitActions"><button class="v2Btn pri" onclick="foodLoad()">Restoranları keşfet</button><button class="v2Btn" onclick="showFoodOrders()">📦 Siparişlerim</button><button class="v2Btn" onclick="showFoodBusiness()">🏪 İşletmem</button></div><div id="foodList" class="section">Yükleniyor…</div></div>');foodLoad()}
async function foodLoad(){const r=document.getElementById('foodList');if(!r)return;try{const a=await Q('GET','food_venues?select=id,name,district,city,cuisine_type,is_open,min_order_amount&is_active=eq.true&order=is_open.desc,name.asc&limit=50');r.innerHTML=a?.length?'<div class="foodGrid">'+a.map(v=>'<button class="foodVenue" onclick="showFoodVenue(\''+E(v.id)+'\')"><b>🍴 '+E(v.name)+'</b><div class="small muted">'+E([v.cuisine_type,v.district,v.city].filter(Boolean).join(' · '))+'</div><span class="foodPill">'+(v.is_open?'🟢 Açık':'⚪ Kapalı')+'</span><span class="foodPill">Min. '+M(v.min_order_amount)+'</span></button>').join('')+'</div>':'<div class="empty">Henüz Yemek işletmesi yok.</div>'}catch(e){r.innerHTML='<div class="error">'+E(e.message||'Restoranlar yüklenemedi.')+'</div>'}}
async function showFoodVenue(id){css();if(!A())return;try{const v=(await Q('GET','food_venues?select=id,name,district,city,cuisine_type,is_open,min_order_amount,delivery_mode&id=eq.'+id+'&limit=1'))?.[0];if(!v)throw Error('İşletme bulunamadı.');const cats=await Q('GET','food_menu_categories?select=id,name&venue_id=eq.'+id+'&is_active=eq.true&order=sort_order.asc,name.asc');const items=await Q('GET','food_menu_items?select=id,category_id,name,description,price_kurus&venue_id=eq.'+id+'&is_available=eq.true&order=sort_order.asc,name.asc');let h='<div><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button><div class="foodHero"><h1>'+E(v.name)+'</h1><div class="small muted">'+E([v.cuisine_type,v.district,v.city].filter(Boolean).join(' · '))+'</div></div>';cats.forEach(c=>{const a=items.filter(i=>i.category_id===c.id);if(!a.length)return;h+='<section class="section"><h2>'+E(c.name)+'</h2>';a.forEach(i=>h+='<div class="foodItem"><div><b>'+E(i.name)+'</b><div class="small muted">'+E(i.description||'')+'</div><b>'+M(i.price_kurus)+'</b></div><button class="foodAdd" onclick="foodAdd(\''+E(v.id)+'\',\''+E(v.name)+'\',\''+E(i.id)+'\',\''+E(i.name)+'\','+(+i.price_kurus||0)+')">＋</button></div>');h+='</section>'});const c=C();if(c.venue?.id===v.id&&c.items.length)h+='<div class="foodCartBar"><b>'+CNT()+' · '+M(SUM())+'</b><button class="v2Btn pri" onclick="showFoodCart()">Sepet →</button></div>';app(h+'</div>')}catch(e){app('<div class="error">'+E(e.message||'Menü yüklenemedi.')+'</div>')}}
function foodAdd(vid,vname,iid,name,price){const c=C();if(c.venue?.id&&c.venue.id!==vid&&c.items.length&&!confirm('Sepet başka bir işletmeye ait. Temizlensin mi?'))return;if(c.venue?.id!==vid)c.items=[];c.venue={id:vid,name:vname};const x=c.items.find(x=>x.menu_item_id===iid);if(x){x.quantity++;x.line_total_kurus=x.quantity*x.unit_price_kurus}else c.items.push({menu_item_id:iid,name_snapshot:name,unit_price_kurus:price,quantity:1,line_total_kurus:price});SAVE(c);showFoodVenue(vid)}
function showFoodCart(){css();if(!A())return;const c=C();if(!c.items.length)return showFoodHome();app('<div><button class="v2Btn sm" onclick="showFoodVenue(\''+E(c.venue.id)+'\')">← Menü</button><div class="foodHero"><h1>'+E(c.venue.name)+'</h1><p class="muted">'+CNT()+' ürün · '+M(SUM())+'</p></div><div class="card"><label>Teslimat<select id="fcMode"><option value="self_delivery">🛵 Teslimat</option><option value="pickup">📦 Gel-al</option></select></label><label>Telefon<input id="fcPhone"></label><label>Adres<textarea id="fcAddress" rows="2"></textarea></label><label>Not<textarea id="fcNote" rows="2"></textarea></label><label>Ödeme<select id="fcPay"><option value="cash_on_delivery">Kapıda nakit</option><option value="card_on_delivery">Kapıda kart</option><option value="agree_with_venue">İşletmeyle anlaşmalı</option></select></label></div><div class="card"><h3>Ürünler</h3>'+c.items.map((x,i)=>'<div class="foodItem"><div><b>'+E(x.name_snapshot)+'</b><div class="small muted">'+x.quantity+' × '+M(x.unit_price_kurus)+'</div></div><div><button class="foodAdd" onclick="foodQty('+i+',-1)">−</button><button class="foodAdd" onclick="foodQty('+i+',1)">＋</button></div></div>').join('')+'</div><div class="foodCartBar"><b>'+M(SUM())+'</b><button class="v2Btn pri" onclick="foodOrder()">Siparişi gönder</button></div></div>')}
function foodQty(i,d){const c=C(),x=c.items[i];if(!x)return;x.quantity+=d;if(x.quantity<=0)c.items.splice(i,1);else x.line_total_kurus=x.quantity*x.unit_price_kurus;if(!c.items.length){CLEAR();return showFoodHome()}SAVE(c);showFoodCart()}
async function foodOrder(){const c=C(),mode=document.getElementById('fcMode')?.value||'pickup',phone=(document.getElementById('fcPhone')?.value||'').trim(),address=(document.getElementById('fcAddress')?.value||'').trim();if(!phone)return alert('Telefon gerekli.');if(mode==='self_delivery'&&!address)return alert('Teslimat adresi gerekli.');try{const rows=await Q('POST','food_orders',{venue_id:c.venue.id,delivery_mode:mode,address_text:mode==='pickup'?null:address,phone,note:(document.getElementById('fcNote')?.value||'').trim(),payment_method:document.getElementById('fcPay')?.value||'cash_on_delivery'}),o=rows?.[0];if(!o?.id)throw Error('Sipariş oluşturulamadı.');await Q('POST','food_order_items',c.items.map(x=>({order_id:o.id,menu_item_id:x.menu_item_id,name_snapshot:x.name_snapshot,unit_price_kurus:x.unit_price_kurus,quantity:x.quantity,line_total_kurus:x.line_total_kurus,options_snapshot:[]})));CLEAR();app('<div class="success"><b>✓ Sipariş alındı.</b><br>#'+E(o.id.slice(0,8).toUpperCase())+'</div><button class="v2Btn pri" onclick="showFoodOrders()">Siparişimi takip et</button>')}catch(e){alert('Sipariş gönderilemedi: '+(e.message||''))}}
async function showFoodOrders(){if(!A())return;try{const a=await Q('GET','food_orders?select=id,status,total_kurus,created_at&order=created_at.desc&limit=30');app('<div><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button><h1>📦 Siparişlerim</h1>'+((a||[]).map(o=>'<div class="foodOrder"><b>#'+E(o.id.slice(0,8).toUpperCase())+'</b> <span class="foodPill">'+E(o.status)+'</span><div class="small muted">'+M(o.total_kurus)+' · '+new Date(o.created_at).toLocaleString('tr-TR')+'</div></div>').join('')||'<div class="empty">Henüz sipariş yok.</div>')+'</div>')}catch(e){app('<div class="error">'+E(e.message||'Siparişler yüklenemedi.')+'</div>')}}
function showFoodBusiness(){if(!A())return;Q('GET','food_venues?select=id,name,is_open,district,city&owner_user_id=eq.'+encodeURIComponent(S().user.id)+'&limit=1').then(v=>{if(!v?.length)return app('<div class="foodShell"><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button><div class="card"><h1>🏪 İşletme kaydı</h1><label>İşletme adı<input id="frName"></label><label>İlçe<input id="frDistrict"></label><label>Telefon<input id="frPhone"></label><button class="v2Btn pri" onclick="foodCreate()">Kaydet</button></div></div>');const x=v[0];app('<div class="foodShell"><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button><div class="foodHero"><h1>🏪 '+E(x.name)+'</h1><span class="foodPill">'+(x.is_open?'🟢 Açık':'⚪ Kapalı')+'</span><div class="splitActions"><button class="v2Btn" onclick="foodOpen(\''+x.id+'\','+(!x.is_open)+')">'+(x.is_open?'Kapat':'Aç')+'</button><button class="v2Btn" onclick="foodMenu(\''+x.id+'\')">📋 Menü</button></div></div><h2>Siparişler</h2><div id="foodOwnerOrders">Yükleniyor…</div></div>');foodOwnerOrders(x.id)}).catch(e=>app('<div class="error">'+E(e.message||'İşletme paneli açılamadı.')+'</div>'))}
async function foodOwnerOrders(v){const r=document.getElementById('foodOwnerOrders');try{const a=await Q('GET','food_orders?select=id,status,total_kurus,phone,delivery_mode,created_at&venue_id=eq.'+v+'&status=neq.cancelled&order=created_at.desc&limit=30');r.innerHTML=a?.map(o=>'<div class="foodOrder"><b>#'+E(o.id.slice(0,8).toUpperCase())+'</b> <span class="foodPill">'+E(o.status)+'</span><div class="small muted">'+M(o.total_kurus)+' · '+E(o.phone)+'</div>'+(o.status==='new'?'<button class="v2Btn pri sm" onclick="foodStatus(\''+o.id+'\',\'accepted\')">Kabul et</button>':o.status==='accepted'?'<button class="v2Btn pri sm" onclick="foodStatus(\''+o.id+'\',\'preparing\')">Hazırla</button>':o.status==='preparing'?'<button class="v2Btn pri sm" onclick="foodStatus(\''+o.id+'\',\'ready\')">Hazır</button>':o.status==='ready'?'<button class="v2Btn pri sm" onclick="foodStatus(\''+o.id+'\',\''+(o.delivery_mode==='self_delivery'?'on_the_way':'delivered')+'\')">'+(o.delivery_mode==='self_delivery'?'Yola çıkar':'Teslim edildi')+'</button>':o.status==='on_the_way'?'<button class="v2Btn pri sm" onclick="foodStatus(\''+o.id+'\',\'delivered\')">Teslim edildi</button>':'')+'</div>').join('')||'<div class="empty">Sipariş yok.</div>'}catch(e){r.innerHTML='<div class="error">'+E(e.message||'Siparişler yüklenemedi.')+'</div>'}}
async function foodCreate(){const n=(document.getElementById('frName')?.value||'').trim();if(!n)return alert('İşletme adı gerekli.');try{await Q('POST','food_venues',{name:n,district:(document.getElementById('frDistrict')?.value||'').trim(),phone:(document.getElementById('frPhone')?.value||'').trim(),city:'İzmir',delivery_mode:'both'});showFoodBusiness()}catch(e){alert(e.message||'Kaydedilemedi.')}}
async function foodOpen(id,on){try{await Q('PATCH','food_venues?id=eq.'+encodeURIComponent(id),{is_open:on});showFoodBusiness()}catch(e){alert(e.message||'Durum değiştirilemedi.')}}
async function foodStatus(id,s){try{await Q('PATCH','food_orders?id=eq.'+encodeURIComponent(id),{status:s});showFoodBusiness()}catch(e){alert(e.message||'Durum değiştirilemedi.')}}
async function foodMenu(v){try{const c=await Q('GET','food_menu_categories?select=id,name&venue_id=eq.'+v+'&order=name.asc'),i=await Q('GET','food_menu_items?select=id,category_id,name,price_kurus,is_available&venue_id=eq.'+v+'&order=name.asc');let h='<div><button class="v2Btn sm" onclick="showFoodBusiness()">← İşletme</button><h1>📋 Menü</h1><div class="card"><input id="fmCat" placeholder="Yeni kategori"><button class="v2Btn pri" onclick="foodCat(\''+v+'\')">Kategori ekle</button></div>';c.forEach(x=>{h+='<section class="section"><h2>'+E(x.name)+'</h2>'+(i.filter(z=>z.category_id===x.id).map(z=>'<div class="foodItem"><b>'+E(z.name)+'<br><span class="small muted">'+M(z.price_kurus)+'</span></b></div>').join('')||'<div class="empty">Ürün yok.</div>')+'</section>'});app(h+'</div>')}catch(e){app('<div class="error">'+E(e.message||'Menü açılamadı.')+'</div>')}}
async function foodCat(v){const n=(document.getElementById('fmCat')?.value||'').trim();if(!n)return;try{await Q('POST','food_menu_categories',{venue_id:v,name:n});foodMenu(v)}catch(e){alert(e.message||'Kategori eklenemedi.')}}
window.showFoodHome=showFoodHome;window.foodLoad=foodLoad;window.showFoodVenue=showFoodVenue;window.showFoodCart=showFoodCart;window.foodAdd=foodAdd;window.foodQty=foodQty;window.foodOrder=foodOrder;window.showFoodOrders=showFoodOrders;window.showFoodBusiness=showFoodBusiness;window.foodCreate=foodCreate;window.foodOpen=foodOpen;window.foodStatus=foodStatus;window.foodMenu=foodMenu;window.foodCat=foodCat;window.openFood=showFoodHome;
})();