/* ISIMI-COZ — Yemek V1 (customer + venue, pilot) */
(()=> {
  if (window.__A7_FOOD_V1__) return;
  window.__A7_FOOD_V1__ = true;
  const CART_KEY='isimi_food_cart_v1';
  const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format((Number(n)||0)/100);
  const esc=v=>typeof window.escapeHTML==='function'?window.escapeHTML(v):String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const session=()=>typeof getAuthSession==='function'?getAuthSession():null;
  const needAuth=()=>{const s=session();if(!s?.access_token||!s?.user?.id){if(typeof openAuthModal==='function')openAuthModal('login');return null;}return s;};
  const req=(method,path,body=null)=>window.supabaseAuthRequest(method,path,body);
  function cart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'null')||{venue:null,items:[],delivery_mode:'self_delivery',payment_method:'cash_on_delivery',address_text:'',phone:'',note:''};}catch(e){return {venue:null,items:[]};}}
  function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));}
  function clearCart(){localStorage.removeItem(CART_KEY);}
  function cartCount(){return cart().items.reduce((n,x)=>n+(Number(x.quantity)||0),0);}
  function cartTotal(){return cart().items.reduce((n,x)=>n+(Number(x.line_total_kurus)||0),0);}
  function foodCss(){
    if(document.getElementById('a7FoodCss'))return;
    const s=document.createElement('style');s.id='a7FoodCss';s.textContent=`
      .foodShell{padding:2px 0 10px}.foodHero{padding:18px 16px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,rgba(20,184,122,.15),var(--card));margin-bottom:12px}.foodSearch{display:flex;gap:8px;margin-top:12px}.foodSearch input{flex:1;min-width:0}.foodGrid{display:grid;grid-template-columns:1fr;gap:10px}.foodVenue{padding:15px;border:1px solid var(--line);border-radius:18px;background:var(--card)}.foodVenueTop{display:flex;gap:10px;align-items:flex-start}.foodVenueIcon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:rgba(20,184,122,.12);font-size:24px;flex:none}.foodMeta{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.foodPill{font-size:11px;color:var(--muted);padding:5px 8px;border:1px solid var(--line);border-radius:999px}.foodMenuCat{margin-top:18px}.foodItem{display:flex;justify-content:space-between;gap:10px;padding:13px 0;border-bottom:1px solid var(--line)}.foodItem:last-child{border-bottom:0}.foodItemInfo{min-width:0}.foodItemName{font-weight:800}.foodItemDesc{font-size:12px;color:var(--muted);margin-top:3px;line-height:1.35}.foodItemPrice{font-weight:900;margin-top:7px}.foodAdd{width:42px;height:42px;border-radius:12px;border:1px solid var(--line);background:var(--card2);color:var(--text);font-size:22px;flex:none}.foodCartBar{position:sticky;bottom:64px;z-index:10;margin-top:12px;padding:10px;border:1px solid var(--line);border-radius:16px;background:var(--card);backdrop-filter:blur(10px);display:flex;align-items:center;gap:8px}.foodCartBar .v2Btn{flex:1}.foodForm{display:grid;gap:10px}.foodForm label{margin:0}.foodOrderCard{padding:14px;border:1px solid var(--line);border-radius:16px;background:var(--card);margin-bottom:10px}.foodStatus{display:inline-flex;padding:5px 9px;border-radius:999px;background:rgba(20,184,122,.12);color:var(--primary);font-size:11px;font-weight:800}.foodOwnerGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.foodOwnerGrid .v2Btn{width:100%}@media(min-width:720px){.foodGrid{grid-template-columns:1fr 1fr}.foodItem{min-height:92px}}html[data-theme="light"] .foodCartBar{background:rgba(255,255,255,.94)}
    `;document.head.appendChild(s);
  }
  async function showFoodHome(){
    foodCss();if(!needAuth())return;if(typeof setNav==='function')setNav('navFood');
    app('<div class="foodShell"><div class="foodHero"><div class="small muted">🍽️ İŞİMİ ÇÖZ YEMEK</div><h1 style="margin:8px 0 6px">Yakınındaki yemekleri bul.</h1><p class="muted" style="margin:0">Yerel restoranlardan keşfet, sepete ekle ve siparişini takip et.</p><div class="foodSearch"><input id="foodSearchInput" placeholder="Restoran, mutfak veya yemek ara"><button class="v2Btn pri" onclick="foodLoadVenues()">Ara</button></div></div><div class="splitActions"><button class="v2Btn" onclick="showFoodOrders()">📦 Siparişlerim</button><button class="v2Btn" onclick="showFoodBusiness()">🏪 İşletmem</button><button class="v2Btn" onclick="showHome()">← Ana sayfa</button></div><div id="foodVenueList" style="margin-top:12px"><div class="notice">Restoranlar yükleniyor…</div></div></div>');
    await foodLoadVenues();
  }
  async function foodLoadVenues(){
    const root=document.getElementById('foodVenueList');if(!root)return;const q=(document.getElementById('foodSearchInput')?.value||'').trim();
    try{const rows=await req('GET','food_venues?select=id,name,phone,address_text,district,city,cuisine_type,is_open,is_active,min_order_amount,delivery_mode&is_active=eq.true&order=is_open.desc,name.asc&limit=50');const filtered=(rows||[]).filter(v=>!q||[v.name,v.cuisine_type,v.district,v.city].join(' ').toLowerCase().includes(q.toLowerCase()));
      if(!filtered.length){root.innerHTML='<div class="empty">Henüz bir Yemek işletmesi bulunmuyor.<br><span class="small">Pilot işletmeler burada görünecek.</span></div>';return;}
      root.innerHTML='<div class="foodGrid">'+filtered.map(v=>`<button type="button" class="foodVenue" style="text-align:left;color:inherit" onclick="showFoodVenue('${esc(v.id)}')"><div class="foodVenueTop"><div class="foodVenueIcon">🍴</div><div style="min-width:0"><div class="foodMeta" style="margin:0 0 5px"><span class="foodPill">${v.is_open?'🟢 Açık':'⚪ Kapalı'}</span>${v.cuisine_type?`<span class="foodPill">${esc(v.cuisine_type)}</span>`:''}</div><strong style="font-size:16px">${esc(v.name)}</strong><div class="small muted" style="margin-top:4px">${esc([v.district,v.city].filter(Boolean).join(' · '))}</div></div></div><div class="foodMeta"><span class="foodPill">Min. ${money(v.min_order_amount)}</span><span class="foodPill">${v.delivery_mode==='pickup'?'📦 Gel-al':v.delivery_mode==='self_delivery'?'🛵 Kendi teslimatı':'🛵/📦 Teslimat + gel-al'}</span></div></button>`).join('')+'</div>';
    }catch(e){console.error(e);root.innerHTML='<div class="error">Restoranlar yüklenemedi. '+esc(e.message||'')+'</div>';}
  }
  async function showFoodVenue(id){
    foodCss();if(!needAuth())return;
    try{const venues=await req('GET','food_venues?select=id,name,phone,address_text,district,city,cuisine_type,is_open,is_active,min_order_amount,delivery_mode&id=eq.'+encodeURIComponent(id)+'&limit=1');const v=venues?.[0];if(!v)throw new Error('İşletme bulunamadı.');const cats=await req('GET','food_menu_categories?select=id,name,sort_order,is_active&venue_id=eq.'+encodeURIComponent(id)+'&is_active=eq.true&order=sort_order.asc,name.asc');const items=await req('GET','food_menu_items?select=id,category_id,name,description,price_kurus,is_available,sort_order&venue_id=eq.'+encodeURIComponent(id)+'&is_available=eq.true&order=sort_order.asc,name.asc');const c=cart();
      let html='<div class="foodShell"><div class="back"><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button></div><div class="foodHero"><div class="small muted">'+(v.is_open?'🟢 Şu an açık':'⚪ Şu an kapalı')+'</div><h1 style="margin:8px 0 4px">'+esc(v.name)+'</h1><div class="muted small">'+esc([v.cuisine_type,v.district,v.city].filter(Boolean).join(' · '))+'</div><div class="foodMeta"><span class="foodPill">Min. '+money(v.min_order_amount)+'</span><span class="foodPill">'+(v.delivery_mode==='pickup'?'Gel-al':v.delivery_mode==='self_delivery'?'Kendi teslimatı':'Teslimat + gel-al')+'</span></div></div>';
      if(!cats?.length)html+='<div class="empty">Bu işletmenin menüsü henüz hazır değil.</div>';else cats.forEach(cat=>{const arr=(items||[]).filter(x=>x.category_id===cat.id);if(!arr.length)return;html+='<section class="foodMenuCat"><h2>'+esc(cat.name)+'</h2>';arr.forEach(it=>{html+='<div class="foodItem"><div class="foodItemInfo"><div class="foodItemName">'+esc(it.name)+'</div>'+(it.description?'<div class="foodItemDesc">'+esc(it.description)+'</div>':'')+'<div class="foodItemPrice">'+money(it.price_kurus)+'</div></div><button class="foodAdd" onclick="foodAddItem(\''+esc(v.id)+'\',\''+esc(v.name)+'\',\''+esc(it.id)+'\',\''+esc(it.name)+'\','+(Number(it.price_kurus)||0)+')">＋</button></div>';});html+='</section>';});
      if(c.venue?.id===v.id&&c.items.length)html+='<div class="foodCartBar"><span><b>'+cartCount()+'</b> ürün · <b>'+money(cartTotal())+'</b></span><button class="v2Btn pri" onclick="showFoodCart()">Sepete git →</button></div>';html+='</div>';app(html);
    }catch(e){app('<div class="error">Menü yüklenemedi: '+esc(e.message||'')+'</div>');}
  }
  function foodAddItem(venueId,venueName,itemId,name,price){const c=cart();if(c.venue?.id&&c.venue.id!==venueId&&c.items.length){if(!confirm('Sepetinde başka bir işletmeden ürün var. Sepeti temizleyip bu işletmeden devam edelim mi?'))return;c.items=[];}c.venue={id:venueId,name:venueName};const x=c.items.find(i=>i.menu_item_id===itemId);if(x){x.quantity+=1;x.line_total_kurus=x.unit_price_kurus*x.quantity;}else c.items.push({menu_item_id:itemId,name_snapshot:name,unit_price_kurus:price,quantity:1,line_total_kurus:price});saveCart(c);showFoodVenue(venueId);}
  function showFoodCart(){foodCss();if(!needAuth())return;const c=cart();if(!c.venue||!c.items.length){app('<div class="empty">Sepetin boş.<br><button class="v2Btn pri" onclick="showFoodHome()" style="margin-top:12px">Yemek keşfet</button></div>');return;}const delivery=c.venue.delivery_mode||'both';let html='<div class="foodShell"><div class="back"><button class="v2Btn sm" onclick="showFoodVenue(\''+esc(c.venue.id)+'\')">← Menü</button></div><div class="foodHero"><div class="small muted">🛒 Sepet</div><h1 style="margin:8px 0 4px">'+esc(c.venue.name)+'</h1><div class="muted small">'+cartCount()+' ürün · '+money(cartTotal())+'</div></div><div class="card"><div class="foodForm"><label>Teslimat<select id="foodDeliveryMode">'+(delivery!=='pickup'?'<option value="self_delivery"'+(c.delivery_mode==='self_delivery'?' selected':'')+'>🛵 Teslimat</option>':'')+(delivery!=='self_delivery'?'<option value="pickup"'+(c.delivery_mode==='pickup'?' selected':'')+'>📦 Gel-al</option>':'')+'</select></label><label>Telefon<input id="foodPhone" value="'+esc(c.phone||'')+'" placeholder="05xx xxx xx xx"></label><label>Adres <span class="small muted">(teslimat seçersen gerekli)</span><textarea id="foodAddress" rows="3" placeholder="Açık adres">'+esc(c.address_text||'')+'</textarea></label><label>Sipariş notu<textarea id="foodNote" rows="2" placeholder="Varsa notun">'+esc(c.note||'')+'</textarea></label><label>Ödeme<select id="foodPayment"><option value="cash_on_delivery">Kapıda nakit</option><option value="card_on_delivery">Kapıda kart</option><option value="agree_with_venue">İşletmeyle anlaşmalı</option></select></label></div></div><div class="card" style="margin-top:10px"><h3>Ürünler</h3>';
    html+=c.items.map((x,i)=>'<div class="foodItem"><div><div class="foodItemName">'+esc(x.name_snapshot)+'</div><div class="small muted">'+x.quantity+' × '+money(x.unit_price_kurus)+'</div></div><div style="display:flex;align-items:center;gap:5px"><button class="foodAdd" style="width:36px;height:36px;font-size:18px" onclick="foodCartQty('+i+',-1)">−</button><b>'+money(x.line_total_kurus)+'</b><button class="foodAdd" style="width:36px;height:36px;font-size:18px" onclick="foodCartQty('+i+',1)">＋</button></div></div>').join('');
    html+='</div><div class="foodCartBar" style="position:static"><span><b>Toplam '+money(cartTotal())+'</b></span><button class="v2Btn pri" onclick="foodSubmitOrder()">Siparişi gönder</button></div></div>';app(html);const p=document.getElementById('foodPayment');if(p)p.value=c.payment_method||'cash_on_delivery';}
  function foodCartQty(i,d){const c=cart(),x=c.items[i];if(!x)return;x.quantity+=d;if(x.quantity<=0)c.items.splice(i,1);else x.line_total_kurus=x.quantity*x.unit_price_kurus;if(!c.items.length){clearCart();return showFoodHome();}saveCart(c);showFoodCart();}
  async function foodSubmitOrder(){const c=cart();if(!c.items.length)return;const mode=document.getElementById('foodDeliveryMode')?.value||'pickup',phone=(document.getElementById('foodPhone')?.value||'').trim(),address=(document.getElementById('foodAddress')?.value||'').trim(),note=(document.getElementById('foodNote')?.value||'').trim(),payment=document.getElementById('foodPayment')?.value||'cash_on_delivery';if(!phone){alert('Telefon numarası gerekli.');return;}if(mode==='self_delivery'&&!address){alert('Teslimat için adres gerekli.');return;}if(!needAuth())return;try{const rows=await req('POST','food_orders',{venue_id:c.venue.id,delivery_mode:mode,address_text:mode==='pickup'?null:address,phone,note,payment_method:payment});const order=Array.isArray(rows)?rows[0]:rows;if(!order?.id)throw new Error('Sipariş oluşturulamadı.');await req('POST','food_order_items',c.items.map(x=>({order_id:order.id,menu_item_id:x.menu_item_id,name_snapshot:x.name_snapshot,unit_price_kurus:x.unit_price_kurus,quantity:x.quantity,line_total_kurus:x.line_total_kurus,options_snapshot:[]})));clearCart();app('<div class="foodShell"><div class="success"><b>✓ Sipariş alındı.</b><br>Sipariş numaran: '+esc(order.id.slice(0,8).toUpperCase())+'</div><div class="card"><h2>Şimdi sırada ne var?</h2><p class="muted">İşletme siparişini kabul ettiğinde durum burada güncellenecek.</p><div class="splitActions"><button class="v2Btn pri" onclick="showFoodOrders()">Siparişimi takip et</button><button class="v2Btn" onclick="showFoodHome()">Yemek keşfet</button></div></div></div>');}catch(e){console.error(e);alert('Sipariş gönderilemedi. '+(e.message||''));}}
  async function showFoodOrders(){foodCss();if(!needAuth())return;try{const rows=await req('GET','food_orders?select=id,venue_id,status,delivery_mode,phone,address_text,note,payment_method,subtotal_kurus,delivery_fee_kurus,total_kurus,created_at,accepted_at,preparing_at,ready_at,on_the_way_at,delivered_at,cancelled_at,cancel_reason&order=created_at.desc&limit=30');app('<div class="foodShell"><div class="back"><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button></div><h1>📦 Siparişlerim</h1><p class="muted">Aktif ve geçmiş siparişlerin.</p><div>'+((rows||[]).map(o=>'<div class="foodOrderCard"><div style="display:flex;justify-content:space-between;gap:8px"><strong>#'+esc(o.id.slice(0,8).toUpperCase())+'</strong><span class="foodStatus">'+foodStatusLabel(o.status)+'</span></div><div class="small muted" style="margin-top:7px">'+esc(o.delivery_mode==='pickup'?'📦 Gel-al':'🛵 Teslimat')+' · '+money(o.total_kurus)+' · '+new Date(o.created_at).toLocaleString('tr-TR')+'</div>'+(o.cancel_reason?'<div class="small" style="margin-top:7px;color:var(--danger)">İptal: '+esc(o.cancel_reason)+'</div>':'')+(o.status==='new'?'<button class="v2Btn sm" style="margin-top:10px" onclick="foodCancelOrder(\''+esc(o.id)+'\')">Siparişi iptal et</button>':'')+'</div>').join('')||'<div class="empty">Henüz siparişin yok.</div>')+'</div></div>');}catch(e){app('<div class="error">Siparişler yüklenemedi: '+esc(e.message||'')+'</div>');}}
  function foodStatusLabel(s){return ({new:'Yeni',accepted:'Kabul edildi',preparing:'Hazırlanıyor',ready:'Hazır',on_the_way:'Yolda',delivered:'Teslim edildi',cancelled:'İptal edildi'})[s]||s;}
  async function foodCancelOrder(id){if(!confirm('Siparişi iptal etmek istediğine emin misin?'))return;try{await req('PATCH','food_orders?id=eq.'+encodeURIComponent(id),{status:'cancelled',cancel_reason:'Müşteri tarafından iptal edildi'});showFoodOrders();}catch(e){alert('İptal edilemedi: '+(e.message||''));}}
  async function showFoodBusiness(){foodCss();if(!needAuth())return;try{const me=session().user.id,venues=await req('GET','food_venues?select=id,name,phone,address_text,district,city,cuisine_type,is_active,is_open,min_order_amount,delivery_mode,working_hours&owner_user_id=eq.'+encodeURIComponent(me)+'&order=created_at.desc');if(!venues?.length)return showFoodBusinessRegister();const v=venues[0],orders=await req('GET','food_orders?select=id,status,delivery_mode,phone,address_text,note,total_kurus,created_at&venue_id=eq.'+encodeURIComponent(v.id)+'&status=neq.cancelled&order=created_at.desc&limit=30');app('<div class="foodShell"><div class="back"><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button></div><div class="foodHero"><div class="small muted">🏪 İşletme paneli</div><h1 style="margin:8px 0 4px">'+esc(v.name)+'</h1><div class="foodMeta"><span class="foodPill">'+(v.is_open?'🟢 Açık':'⚪ Kapalı')+'</span><span class="foodPill">'+esc(v.district||v.city||'İzmir')+'</span></div><div class="foodOwnerGrid" style="margin-top:10px"><button class="v2Btn" onclick="foodToggleOpen(\''+esc(v.id)+'\','+(v.is_open?'false':'true')+')">'+(v.is_open?'🔴 Kapat':'🟢 Aç')+'</button><button class="v2Btn" onclick="showFoodMenuManage(\''+esc(v.id)+'\')">📋 Menüyü yönet</button></div></div><h2>Gelen siparişler</h2><div>'+((orders||[]).map(o=>'<div class="foodOrderCard"><div style="display:flex;justify-content:space-between;gap:8px"><strong>#'+esc(o.id.slice(0,8).toUpperCase())+'</strong><span class="foodStatus">'+foodStatusLabel(o.status)+'</span></div><div class="small muted" style="margin-top:7px">'+esc(o.delivery_mode==='pickup'?'📦 Gel-al':'🛵 Teslimat')+' · '+money(o.total_kurus)+'</div><div class="small" style="margin-top:7px">📞 '+esc(o.phone)+(o.address_text?' · 📍 '+esc(o.address_text):'')+'</div>'+(o.note?'<div class="small muted" style="margin-top:5px">Not: '+esc(o.note)+'</div>':'')+'<div class="splitActions" style="margin-top:9px">'+foodOwnerStatusButtons(o)+'</div></div>').join('')||'<div class="empty">Henüz sipariş yok.</div>')+'</div></div>');}catch(e){app('<div class="error">İşletme paneli yüklenemedi: '+esc(e.message||'')+'</div>');}}
  function foodOwnerStatusButtons(o){const next={new:['accepted','Kabul et'],accepted:['preparing','Hazırlamaya başla'],preparing:['ready','Hazır'],ready:o.delivery_mode==='self_delivery'?['on_the_way','Yola çıkar']:['delivered','Teslim edildi'],on_the_way:['delivered','Teslim edildi']}[o.status];let h=next?'<button class="v2Btn pri sm" onclick="foodSetOrderStatus(\''+esc(o.id)+'\',\''+next[0]+'\')">'+next[1]+'</button>':'';if(['new','accepted','preparing','ready','on_the_way'].includes(o.status))h+='<button class="v2Btn sm" onclick="foodOwnerCancel(\''+esc(o.id)+'\')">İptal et</button>';return h;}
  async function foodSetOrderStatus(id,status){try{await req('PATCH','food_orders?id=eq.'+encodeURIComponent(id),{status});showFoodBusiness();}catch(e){alert('Durum güncellenemedi: '+(e.message||''));}}
  async function foodOwnerCancel(id){if(!confirm('Siparişi iptal etmek istiyor musun?'))return;try{await req('PATCH','food_orders?id=eq.'+encodeURIComponent(id),{status:'cancelled',cancel_reason:'İşletme tarafından iptal edildi'});showFoodBusiness();}catch(e){alert('İptal edilemedi: '+(e.message||''));}}
  function showFoodBusinessRegister(){app('<div class="foodShell"><div class="back"><button class="v2Btn sm" onclick="showFoodHome()">← Yemek</button></div><div class="foodHero"><div class="small muted">🏪 İşletme kaydı</div><h1 style="margin:8px 0">Yemek işletmeni ekle.</h1><p class="muted">Pilot aşamada 1 işletme hesabından tek işletme yönetiyoruz.</p></div><div class="card"><div class="foodForm"><label>İşletme adı<input id="fbName" placeholder="Örn. İzmir Ev Yemekleri"></label><label>Telefon<input id="fbPhone" placeholder="05xx xxx xx xx"></label><label>İlçe<input id="fbDistrict" placeholder="Karşıyaka"></label><label>Adres<input id="fbAddress" placeholder="Açık adres"></label><label>Mutfak türü<input id="fbCuisine" placeholder="Ev yemekleri, kebap, pizza…"></label><label>Minimum sipariş (TL)<input id="fbMin" type="number" min="0" step="1" value="0"></label><label>Teslimat modeli<select id="fbMode"><option value="both">Teslimat + gel-al</option><option value="self_delivery">Kendi teslimatım</option><option value="pickup">Sadece gel-al</option></select></label><button class="v2Btn pri" onclick="foodCreateVenue()">İşletmeyi kaydet</button></div></div></div>');}
  async function foodCreateVenue(){const name=(document.getElementById('fbName')?.value||'').trim();if(!name){alert('İşletme adı gerekli.');return;}try{await req('POST','food_venues',{name,phone:(document.getElementById('fbPhone')?.value||'').trim(),district:(document.getElementById('fbDistrict')?.value||'').trim(),address_text:(document.getElementById('fbAddress')?.value||'').trim(),city:'İzmir',cuisine_type:(document.getElementById('fbCuisine')?.value||'').trim(),min_order_amount:Math.max(0,Math.round((Number(document.getElementById('fbMin')?.value)||0)*100)),delivery_mode:document.getElementById('fbMode')?.value||'both',is_active:true,is_open:false});showFoodBusiness();}catch(e){alert('İşletme kaydedilemedi: '+(e.message||''));}}
  async function foodToggleOpen(id,on){try{await req('PATCH','food_venues?id=eq.'+encodeURIComponent(id),{is_open:!!on});showFoodBusiness();}catch(e){alert('İşletme durumu değiştirilemedi: '+(e.message||''));}}
  async function showFoodMenuManage(venueId){try{const cats=await req('GET','food_menu_categories?select=id,name,sort_order,is_active&venue_id=eq.'+encodeURIComponent(venueId)+'&order=sort_order.asc,name.asc'),items=await req('GET','food_menu_items?select=id,category_id,name,description,price_kurus,is_available,sort_order&venue_id=eq.'+encodeURIComponent(venueId)+'&order=sort_order.asc,name.asc');let html='<div class="foodShell"><div class="back"><button class="v2Btn sm" onclick="showFoodBusiness()">← İşletme</button></div><h1>📋 Menü</h1><p class="muted">Kategori ve ürünlerini burada yönet.</p><div class="card"><h3>Yeni kategori</h3><div class="foodForm"><input id="fmCat" placeholder="Örn. Ana yemekler"><button class="v2Btn pri" onclick="foodAddCategory(\''+esc(venueId)+'\')">Kategori ekle</button></div></div><div class="card" style="margin-top:10px"><h3>Yeni ürün</h3><div class="foodForm"><select id="fmCatSel">'+(cats||[]).map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select><input id="fmName" placeholder="Ürün adı"><input id="fmDesc" placeholder="Kısa açıklama"><input id="fmPrice" type="number" min="0" step="0.01" placeholder="Fiyat TL"><button class="v2Btn pri" onclick="foodAddItemManage(\''+esc(venueId)+'\')">Ürün ekle</button></div></div><div style="margin-top:12px">'+(cats||[]).map(c=>'<section class="foodMenuCat"><h2>'+esc(c.name)+'</h2>'+((items||[]).filter(i=>i.category_id===c.id).map(i=>'<div class="foodItem"><div><b>'+esc(i.name)+'</b><div class="small muted">'+money(i.price_kurus)+' · '+(i.is_available?'Satışta':'Pasif')+'</div></div><button class="v2Btn sm" onclick="foodToggleItem(\''+esc(i.id)+'\','+(i.is_available?'false':'true')+',\''+esc(venueId)+'\')">'+(i.is_available?'Pasifleştir':'Aktifleştir')+'</button></div>').join('')||'<div class="small muted">Bu kategoride ürün yok.</div>')+'</section>').join('')+'</div></div>';app(html);}catch(e){app('<div class="error">Menü yüklenemedi: '+esc(e.message||'')+'</div>');}}
  async function foodAddCategory(venueId){const name=(document.getElementById('fmCat')?.value||'').trim();if(!name){alert('Kategori adı gerekli.');return;}try{await req('POST','food_menu_categories',{venue_id:venueId,name,sort_order:0,is_active:true});showFoodMenuManage(venueId);}catch(e){alert('Kategori eklenemedi: '+(e.message||''));}}
  async function foodAddItemManage(venueId){const cat=document.getElementById('fmCatSel')?.value,name=(document.getElementById('fmName')?.value||'').trim(),price=Math.round((Number(document.getElementById('fmPrice')?.value)||0)*100);if(!cat||!name||price<0){alert('Kategori, ürün adı ve fiyat gerekli.');return;}try{await req('POST','food_menu_items',{venue_id:venueId,category_id:cat,name,description:(document.getElementById('fmDesc')?.value||'').trim(),price_kurus:price,is_available:true,sort_order:0});showFoodMenuManage(venueId);}catch(e){alert('Ürün eklenemedi: '+(e.message||''));}}
  async function foodToggleItem(id,on,venueId){try{await req('PATCH','food_menu_items?id=eq.'+encodeURIComponent(id),{is_available:!!on});showFoodMenuManage(venueId);}catch(e){alert('Ürün durumu değiştirilemedi: '+(e.message||''));}}
  window.showFoodHome=showFoodHome;window.showFoodVenue=showFoodVenue;window.showFoodCart=showFoodCart;window.foodAddItem=foodAddItem;window.foodCartQty=foodCartQty;window.foodSubmitOrder=foodSubmitOrder;window.showFoodOrders=showFoodOrders;window.foodCancelOrder=foodCancelOrder;window.showFoodBusiness=showFoodBusiness;window.foodCreateVenue=foodCreateVenue;window.foodToggleOpen=foodToggleOpen;window.showFoodMenuManage=showFoodMenuManage;window.foodAddCategory=foodAddCategory;window.foodAddItemManage=foodAddItemManage;window.foodToggleItem=foodToggleItem;window.foodSetOrderStatus=foodSetOrderStatus;window.foodOwnerCancel=foodOwnerCancel;window.openFood=showFoodHome;
})();